fn-call:
  identifier foo
  error
